---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-depl
  labels:
    type: proxy
spec:
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
