---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    type: mydb
spec:
  replicas: 2
  selector:
    matchLabels:
      type: mydb
  template:
    metadata:
      name: mysql
      labels:
        type: mydb
    spec:
      containers:
        - name: mysql
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: viky
