---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ghost-rs
  labels:
    type: cms
spec:
  replicas: 2
  selector:
    matchLabels:
      type: cms
  template:
    metadata:
      name: ghost-rs
      labels:
        type: cms
    spec:
      containers:
        - name: ghost-pod
          image: ghost
          ports:
            - containerPort: 2368
              hostPort: 1122
          env:
            - name: NODE_ENV
              value: development
