---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myhttpd
  labels:
    type: webserver
spec:
  replicas: 3
  template:
    metadata:
      name: myhttpd
      labels:
        type: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 1122
