---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  labels:
    type: mydb
spec:
  containers:
    - name: postgres-db
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: 12345
          name: POSTGRES_USER
          value: myuser
          name: POSTGRES_DB
          value: mydb
