---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    type: port
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30018
  selector:
    type: webserver
