---
apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    type: port1
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: proxy
